# Generated by Django 5.0.1 on 2024-01-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('restaurants', '0002_menu_is_available_menu_is_vegetarian_menu_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
